version: '3.9'

services:
  inst_db:
    container_name: inst_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    image: postgres:16.3-alpine3.20
